[versions]
agp = "8.7.3"
gamesActivity = "4.4.0"
appcompat = "1.6.1"
material = "1.10.0"

[libraries]
games-activity = { group = "androidx.games", name = "games-activity", version.ref = "gamesActivity" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }